### ISSUE TITLE
Return empty list for concepts of unsupported concept schemes

### ISSUE THREAD

**Issue by stefandesu** [gbv/subjects-api#11]
Right now, if a concept of an unsupported concept scheme is given, the API returns a 404 page, see [this example](https://coli-conc.gbv.de/occurrences/api/occurrences?member=http://www.wikidata.org/entity/Q42395&scheme=*&threshold=5&database=opac-de-627). Wouldn't it be better if it just returned an empty list?

**Comment by nichtich** [comment]
Maybe, but then we have no information about why no results are returned.

**Comment by stefandesu** [comment]
Yeah, I mean this issue is almost three years old. Nowadays I would suggest providing a list of compatible concept schemes via the `/status` endpoint or something like that. We have `mappings.fromSchemeWhitelist` and `mappings.toSchemeWhitelist`, for example.
