### ISSUE TITLE
Return plain occurrences if no scheme is given

### ISSUE THREAD

**Issue by nichtich** [gbv/subjects-api#16]
From documentation of the previous implementation:

> Occurrences are returned if no scheme is given, co-occurrences are returned otherwise

Plain occurrences only have the queried member in `memberSet` and count the total number of distinct PPN so `count(*) AS freq FROM subjects WHERE voc=? and notation=?` should do. The result can be used by clients to calculate frequency and to show how many records are indexed with a specific subject.

**Comment by nichtich** [comment]
Given the CQL key of a vocabulary, the *current* occurrence number (from live K10plus) could be retrieved via SRU, e.g. for ddc notation `335.83092`:

http://sru.k10plus.de/opac-de-627?version=1.1&operation=searchRetrieve&recordSchema=picaxml&startRecord=1&maximumRecords=0&query=pica.ddc%3D335.83092

Extract the result via regex `/numberOfRecords>([0-9]+)</`.

This would be an additional feature, maybe enabled with flag such as `cache=false`. Including a recent `Last-Modified` would indicate that the result is actually live.

**Comment by stefandesu** [comment]
Currently, when no scheme is given, co-occurrences for any target scheme are returned. I think this behavior should remain in some capacity, whether it is with a special value (`scheme=*`) or some other way.

**Comment by nichtich** [comment]
When no scheme was given, occurrences were returned in the previous implementation. This behavior should be restored. The special value `scheme=*` should return co-occurrences for any target scheme. So existence of parameter `scheme` enables co-occurrence in contrast to occurrences.

**Comment by stefandesu** [comment]
> When no scheme was given, occurrences were returned in the previous implementation. This behavior should be restored. The special value `scheme=*` should return co-occurrences for any target scheme. So existence of parameter `scheme` enables co-occurrence in contrast to occurrences.

Sounds good! Not related to this repo, but in practice, Cocoda will only show co-occurrences as mapping recommendations, right? I'm not sure if cocoda-sdk even supports normal occurrences (because it converts the API results to a mapping for Cocoda). 🤔

**Comment by nichtich** [comment]
Cocoda will only show co-occurrences so far, but search links could be extended to show the actual number of publications in place of the static link. Likely related to https://github.com/gbv/bartoc.org/issues/76.

**Comment by stefandesu** [comment]
One question: Should occurrences be returned as an array as well, even if it's only one result? I couldn't find out if that was the case with the old implementation. Or should we support multiple inputs separated by `|` for the `member` parameter?

**Comment by nichtich** [comment]
Better always return an array, so empty result is possible via empty array.

**Comment by stefandesu** [comment]
Returning plain occurrences is now supported. Live results directly from K10plus should be a separate issue.
