### ISSUE TITLE
Make it easier to provide the database file

### ISSUE THREAD

**Issue by nichtich** [gbv/subjects-api#17]
A command line script to import from TSV file should do, basically like [this SQL statement](https://github.com/gbv/k10plus-subjects/blob/main/import-subjects.sql). This could also be used to setup testing.

**Comment by nichtich** [comment]
The service should automatically create the database file. The documentation should tell how to import data from https://doi.org/10.5281/zenodo.7016625.

Basically it's:

    URL=$(curl -sL "https://zenodo.org/api/records/7016625" | jq -r '.files[]|select(.key|endswith(".tsv.gz"))|.links.self')
    sqlite3 $DATABASE < setup.sql
    curl -sL $URL | zcat | sqlite3 $DATABASE -cmd ".mode tabs" ".import /dev/stdin subjects"
    
I've removed SQLite from https://github.com/gbv/k10plus-subjects so here's the new `setup.sql`

~~~sql
CREATE TABLE IF NOT EXISTS subjects (
  ppn TEXT NOT NULL,
  voc TEXT NOT NULL,
  notation TEXT NOT NULL
);
DELETE FROM subjects;
CREATE INDEX idx_notation on subjects (notation);
CREATE INDEX idx_ppn on subjects (ppn);
~~~

**Comment by stefandesu** [comment]
Sounds good. I still have to investigate the performance issues though. Currently on our server it's pretty slow, although it mostly works fine on my local machine. Might be related to drive speeds. If we use a hosted PostgreSQL database, we might get much better performance. In theory, it wouldn't be a big deal to support both SQLite and PostgreSQL, and we could offer a tiny setup script that differentiates between the two.

**Comment by nichtich** [comment]
The current TSV file is less than 2GB decompressed so the full database should better come from memory anyway. As far as what I've read SQLite does not help to do so as it only reads pages from disk. I guess PostgreSQL is better [to hold database in memory]( https://dba.stackexchange.com/questions/2041/postgresql-force-data-into-memory).

**Comment by stefandesu** [comment]
It would also be possible to keep the SQLite database in a RAM disk, but that's more of a hack to be honest. I guess using PostgreSQL would be better.
