### ISSUE TITLE
Add HTML client

### ISSUE THREAD

**Issue by nichtich** [gbv/subjects-api#19]
The description page (#18) should include a HTML client, consisting of a web form to query and display (co)-occurrences for K10plus.

**Comment by nichtich** [comment]
This should include:

1. Input field and button to type in a PPN and get list of subjects of this record (`/subjects` endpoint)
2. Input field(s) and to select a concept (via URI or via Notation + Vocabulary) and button to query occurrences
3. Additional selection of co-vocabulary and button to query co-occurrences

Results should be clickable to select concept from subjects or co-occurrences as new concept to query (co-)occurrences from.

User interface for editing subjects may better be done in a later release or not part of subjects-api at all as we will use a different UI for editing anyway (see <https://github.com/gbv/coli-rich-web/blob/main/mockup.png>).

**Comment by stefandesu** [comment]
A basic client for loading subjects for a title is now added. Anything else will be tracked in #54.
