### ISSUE TITLE
Include deep link URL into K10plus

### ISSUE THREAD

**Issue by nichtich** [gbv/subjects-api#23]
At least plain occurrences should include a deep link into K10plus in field `url`. Unfortunately this depends on vocabulary.

- `https://opac.k10plus.de/DB=2.299/CMD?ACT=SRCHA&IKT=8533&TRM=gnd+{notation}` for GND
- `https://opac.k10plus.de/DB=2.299/CLK?IKT=5004&TRM={notation}` for BK
- `https://opac.k10plus.de/DB=2.299/CLK?IKT=3002&NOABS=Y&TRM={notation}` for RVK
- `https://opac.k10plus.de/DB=2.299/CMD?ACT=SRCHA&IKT=8506&TRM={notation}` for LCSH and LCNAF

See also https://github.com/gbv/bartoc.org/issues/76#issuecomment-872896373

**Comment by stefandesu** [comment]
Thanks. There are no URLs for Co-Occurrences yet, right?

**Comment by nichtich** [comment]
I think it is possible to craft URLs for some combinations of vocabularies but this requires someone with more knowledge in PICA/PSI Indexing.

**Comment by nichtich** [comment]
To support deep links to co-occurrences into K10plus, each concept scheme must be searchable by IKT, e.g.

- RVK: IKT 3002
- BK: IKT 5004

Deep link co-occurence RVK `UB 4050` and BK `33.99`:

https://opac.k10plus.de/DB=2.299/CMD?ACT=SRCHM&ACT0=SRCHA&IKT0=3002&TRM0=UB%204050&ACT1=*&IKT1=5004&TRM1=33.99

I've added additional key `IKT` to [links.json](https://github.com/gbv/occurrences-api/blob/main/links.json) (by now there is IKT for each vocabulary this was not the case earlier and may change with addition of more vocabularies). So when both schemes have IKT, deep link should be

`https://opac.k10plus.de/DB=2.299/CMD?ACT=SRCHM&ACT0=SRCHA&IKT0={{scheme1.IKT}}&TRM0={{notation1}}&ACT1=*&IKT1={{scheme2.IKT}}&TRM1={{notation2}}`
