### ISSUE TITLE
Include modification date 

### ISSUE THREAD

**Issue by nichtich** [gbv/subjects-api#25]
The API results are dated. At the moment the dump is from 2022-06-30, so this date should be included in responses. See also #24 to increase update frequency.

**Comment by nichtich** [comment]
Could be part of #27.

**Comment by stefandesu** [comment]
Should the date be the import date? What if the imported dump is actually older than the import date?

**Comment by nichtich** [comment]
Modification date taken in this order:

- explicit date given to update script via command line script (e.g. `--modified`)
- else if import file given explicitly to import script (no import from stdin): use date of timestamp of import file
- else use current date

The date should best persitently be stored by the backend (in SQL database or in a file)

**Comment by stefandesu** [comment]
Now added in import script and API results.
