### ISSUE TITLE
Add import script

### ISSUE THREAD

**Issue by nichtich** [gbv/subjects-api#27]
Import of backend data from TSV file should be executed by a script so we can import the same way in multiple backend (seee #26).

**Comment by nichtich** [comment]
To also solve #24, the script could have option to purge database content (default, used when importing a fill dump) or to do an incremental update (likely much slower as it requires to query the backend).

**Comment by stefandesu** [comment]
For some reason, I've been tagging the commits related to this with #24.

There's now a basic working implementation of the import script. Things that are missing:

- [ ] Better error handling
- [ ] Documentation
