### ISSUE TITLE
Add backend for live date

### ISSUE THREAD

**Issue by nichtich** [gbv/subjects-api#34]
At least simple occurences and subjects can be queried live via SRU for exact up-to-date data.

**Comment by nichtich** [comment]
To get subjects of a known record, unAPI can be used and extraction of subjects as implemeted at https://github.com/gbv/k10plus-subjects/blob/main/extract-subjects.pl

To search for records with known subject, SRU is needed.

**Comment by stefandesu** [comment]
The code has since been merged into dev and deployed to https://coli-conc.gbv.de/subjects-k10plus/. I think the `extractSubjects` code should be reviewed and tested, though: https://github.com/gbv/subjects-api/blob/dev/src/extract-subjects.js
